CREATE TABLE ranked_runs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
  played_on date NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'in_progress'
    CHECK (status IN ('in_progress', 'completed')),
  score integer NOT NULL DEFAULT 0 CHECK (score BETWEEN 0 AND 140),
  swiss_wins smallint NOT NULL DEFAULT 0 CHECK (swiss_wins BETWEEN 0 AND 3),
  quarterfinal_won boolean NOT NULL DEFAULT false,
  semifinal_won boolean NOT NULL DEFAULT false,
  final_won boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  CONSTRAINT ranked_runs_one_per_day UNIQUE (user_id, played_on)
);

CREATE TABLE ranked_run_events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id integer NOT NULL REFERENCES ranked_runs(id) ON DELETE CASCADE,
  event_key varchar(80) NOT NULL,
  event_type varchar(30) NOT NULL
    CHECK (event_type IN ('swiss_win', 'quarterfinal_win', 'semifinal_win', 'final_win')),
  points smallint NOT NULL CHECK (points IN (10, 30, 50)),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ranked_events_key_once UNIQUE (run_id, event_key)
);

CREATE UNIQUE INDEX ranked_events_quarterfinal_once
  ON ranked_run_events (run_id, event_type) WHERE event_type = 'quarterfinal_win';
CREATE UNIQUE INDEX ranked_events_semifinal_once
  ON ranked_run_events (run_id, event_type) WHERE event_type = 'semifinal_win';
CREATE UNIQUE INDEX ranked_events_final_once
  ON ranked_run_events (run_id, event_type) WHERE event_type = 'final_win';
CREATE INDEX ranked_runs_user_idx ON ranked_runs (user_id);
CREATE INDEX ranked_runs_score_idx ON ranked_runs (score DESC);

