ALTER TABLE app_users ALTER COLUMN password_hash DROP NOT NULL;

CREATE TABLE user_oauth_identities (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
  provider varchar(30) NOT NULL,
  provider_subject varchar(255) NOT NULL,
  email varchar(254),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_oauth_provider_subject_unique UNIQUE (provider, provider_subject),
  CONSTRAINT user_oauth_user_provider_unique UNIQUE (user_id, provider)
);

CREATE TABLE oauth_login_states (
  state_hash char(64) PRIMARY KEY,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE oauth_exchange_codes (
  code_hash char(64) PRIMARY KEY,
  user_id integer NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX oauth_login_states_expiry_idx ON oauth_login_states (expires_at);
CREATE INDEX oauth_exchange_codes_expiry_idx ON oauth_exchange_codes (expires_at);

