CREATE TABLE game_notifications (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(120) NOT NULL,
  message text NOT NULL,
  type varchar(20) NOT NULL DEFAULT 'news'
    CHECK (type IN ('news', 'update', 'warning', 'maintenance')),
  status varchar(20) NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'published')),
  published_at timestamptz,
  expires_at timestamptz,
  created_by integer REFERENCES app_users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT game_notifications_valid_period CHECK (
    expires_at IS NULL OR published_at IS NULL OR expires_at > published_at
  )
);

CREATE INDEX game_notifications_public_idx
  ON game_notifications (published_at DESC)
  WHERE status = 'published';

